### ISSUE TITLE
panic: unimplemented: prec=1013

### ISSUE THREAD

**Issue by hiwane** [hiwane/ganrac#17]
```
22:40:11 [31,2]           qe: 536:   cad[  2,  3] all([y,z,w], w-y+1<=0 || w-y-1>=0 || ((z-x==0 || w+y==0) && (w==0 || (y-1)*w-z^2+x*z==0)) || (4*w^2-8*y*w+3*z^2+4*y^2-4<0 && ((z-x!=0 && w+y!=0) || (w!=0 && (y-1)*w-z^2+x*z!=0))))

--- information about the cell [703 20] 0xc0029e54a0 ---
lv=1:y, de=true, exdeg=1, truth=-1 sgn=1
# of children=-1
def.poly     =9*y^4-42*y^2-12*x^2+49
signature    =(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0)
iso.nintv    =[-0.406452,-0.406452]
             =[-4.064519e-01,-4.064519e-01] = 0.000000e+00
panic: unimplemented: prec=1013

goroutine 1 [running]:
github.com/hiwane/ganrac.(*Cell).improveIsoIntv(0xc0029e54a0, 0xc001366570?, 0x80?)
        /home/iwane/prog/go/src/github.com/hiwane/ganrac/lift.go:1318 +0x1b9
github.com/hiwane/ganrac.(*CAD).symde_zero_chk2(0x40c04a?, 0x18?, 0x5d9340?, 0x1?)
        /home/iwane/prog/go/src/github.com/hiwane/ganrac/cad_de.go:252 +0xa7
github.com/hiwane/ganrac.(*CAD).sym_zero_chk(0xc001d3b780?, 0x2?, 0x60f145?)
        /home/iwane/prog/go/src/github.com/hiwane/ganrac/cad_de.go:177 +0x58
github.com/hiwane/ganrac.(*CAD).sym_equal(0xc001366570?, 0xc0029e54a0, 0xc0029e55e0)
        /home/iwane/prog/go/src/github.com/hiwane/ganrac/cad_de.go:166 +0x245
github.com/hiwane/ganrac.(*CAD).cellmerge2(0xc0005e81c0, {0xc0029b60e0, 0x1c, 0x8?}, {0xc001b06048, 0x2, 0xc00009af30?}, 0x1)
 
```

**Comment by hiwane** [comment]
```
F = all([y,z,w], w-y+1<=0 || w-y-1>=0 || ((z-x==0 || w+y==0) && (w==0 || (y-1)*w-z^2+x*z==0)) || (4*w^2-8*y*w+3*z^2+4*y^2-4<0 && ((z-x!=0 && w+y!=0) || (w!=0 && (y-1)*w-z^2+x*z!=0))));
C = cadinit(F);
cadproj(C);
verbose(1, 2);
cadlift(C, 703, 20);
```
